### ISSUE TITLE
[Question] Is this library support still alive?

### ISSUE THREAD

**Issue by ronjunelopez** [xaguzman/pathfinding#12]

**Comment by xaguzman** [comment]
I am still using it, I just havent put any more code into it, since so far
it has solved my needs and I don't think there are many more users using
the library.

So yeah, to a degree, but it just doesnt have the same amount of time being
dedicated to it

---------------------------
*Xavier Guzman*

<http://blog.xavierguzman.com>
<http:////plus.google.com/u/0/113140404022814604923?>
<http://mx.linkedin.com/in/xavierguz/>       <https://twitter.com/arkalain>

Blog <http://blog.xavierguzman.com>   |  G+
<http:////plus.google.com/u/0/113140404022814604923?>  | LinkedIn
<http://mx.linkedin.com/in/xavierguz/> | Twitter
<https://twitter.com/arkalain>

**Comment by ronjunelopez** [comment]
@xaguzman your library is awesome!, a beginner like me in `AI` path-finding programming will benefit a lot. I hope there's a lot more enhancement like for a versatility of the library. Kudos!
